### ISSUE TITLE
post navigation floating issue on small screens

### ISSUE THREAD

**Issue by bahnfrei** [niklasbuschmann/contrast#23]
Hi Niklas,

the latest change has a bad effect on post navigation floating on small screens:

623840a
![Screenshot 2020-03-18 at 21 02 47](https://user-images.githubusercontent.com/10193241/77047344-de29a880-69c4-11ea-9986-7a87cb242609.png)

vs.

3edaa05
![Screenshot 2020-03-18 at 21 03 38](https://user-images.githubusercontent.com/10193241/77047316-d4a04080-69c4-11ea-93ac-aa26087347e0.png)

Best regards, Michi.

**Comment by niklasbuschmann** [comment]
The main issue is here that the right-alignment only makes sense when the divs don't break and css seems to have no ability to set the alignment based on this condition, but I might be wrong here.

So I decided to let the divs always break on small screens and give them half width and alignment otherwise.

I hope this works for you, but I'm open for other solutions.

**Comment by bahnfrei** [comment]
it could do the trick ;-) i'm not aware of other possible solutions...

thank you!
