### ISSUE TITLE
Footer in archive not functioning properly

### ISSUE THREAD

**Issue by akarki15** [niklasbuschmann/contrast#3]
Footer in archive acts weird and shows up immediately below the list of posts rather than at the bottom of the page.

**Comment by niklasbuschmann** [comment]
This is a common problem with CSS, search for *sticky footer* on google.

You can fix the problem by setting an explicit height on the footer and give the html, body and article an min-width of 100% and the article a negative bottom margin of the footer height.

I will try to include a fix when I'm back from holiday.

**Comment by m3adow** [comment]
Did you manage to look into this issue? I'm in the process of setting up a Jekyll blog with your theme, but this issue bugs me a lot.
I tried fixing it myself, but haven't been successful yet.

**Comment by niklasbuschmann** [comment]
The solution I [suggested above](https://github.com/niklasbuschmann/contrast/issues/3#issuecomment-106003893) doesn't work if the article is higher than the monitor height.

I used the CSS 3 flexboxes, which works with [all evergreen browsers](http://caniuse.com/#feat=flexbox), otherwise the site will be displayed as before.

See [this commit](https://github.com/niklasbuschmann/contrast/commit/603dabd98bca47fdc7fd5a57a4164a94186c287e) for the major changes and this [example](http://niklasbuschmann.github.io/contrast/archive.html).

This bug should be fixed, feel free to report any problems.
