### ISSUE TITLE
custom style and variables

### ISSUE THREAD

**Issue by bahnfrei** [niklasbuschmann/contrast#7]
Hi Niklas,
first of all i'd like to thank you for your great job! I use your theme since last years summer and it fits pretty good...
Now i found your redesign and started to adapt it (merge in my customisations). I'd like to collect all my changes in a custom style, which is not that difficult. So i created `assets/css/custom.sass` (based on `assets/css/contrast.sass`) and enabled it in `_config.yml` (`style: custom`). To overwrite some of the predefined variables i set it in `custom.sass` before `@import anchor`. This works in most cases, but not always. The "issues" i figured out are caused by `assets/css/index.css` and `assets/css/default.css` which load the default values via `@import`'s as well.
because i wanted to change as little as possible of the original code, i assumed that i could do everything with my own style. but it looks like i'd have to directly adjust the values in `_sass/variables.sass` instead? Or do you see another option?
Thanks in advance and best regards, Michi.

**Comment by niklasbuschmann** [comment]
Hello Bahnfrei,

I'm glad you like my theme :-)

Your approach seems pretty straightforward, this is how I would have done it myself.

Could you tell me which variables are causing problems or give me an example where your approach works and where it doesn't?

**Comment by bahnfrei** [comment]
Hi Niklas,

with the following code in `assets/css/custom.sass`

```
---
---

$link-color: #09c

@import anchor

body > header, article, body > footer
  padding: 1.5em calc(25% - 4.5rem)

article, body > footer
  border-top: 1px solid reduce(40)

body > header
  background: $link-color
  color: #fff

body > footer
  background: reduce(5)
  color: reduce(100)
```

Sometime links appear in the default color during page load or while switching between pages. So i did a quick search for the default color code and found the following in the build result:

```
$ find _site/ -name *css -type f -exec grep -H 68f {} \;
_site//assets/css/contrast.css:  background: #68f;
_site//assets/css/contrast.css:  box-shadow: 0 0 0 2px #68f inset;
_site//assets/css/contrast.css:  color: #68f; }
_site//assets/css/index.css:  color: #68f; }
_site//assets/css/index.css:  border-left: 4px solid #68f;
_site//assets/css/default.css:  background: #68f;
_site//assets/css/default.css:  box-shadow: 0 0 0 2px #68f inset;
_site//assets/css/default.css:  color: #68f; }
```

It's not there, if i change the color directly in `_sass/variables.sass`

Do you need additional information?

**Comment by niklasbuschmann** [comment]
Hello Bahnfrei,

First of all, I noticed the flash of colour during page load myself some time ago. It started to appear at a time when I didn't change anything on the theme and I was only able to reproduce it on Chrome. So - I might be completely wrong here - but I suspect this could be a Chrome issue and has probably nothing to do with the variables issue. 

Now the sass variables are scoped locally so setting a variable will only change the variable in this file, which usually is not a problem. The problem here is the weak separation between the core-theme (index.css and classes.css) and the decoration (default.css, contrast.css, custom.css - of which only one will be loaded). So there is now a different $link-color for index.css (affecting the color of links in an article and the color of the blockquote border) and custom.css (affecting the color of the read-more buttons).

This is clearly an issue on my side and I will look into it more deeply tomorrow, although I can't promise anything.

Best regards,

Niklas

**Comment by bahnfrei** [comment]
Hi Niklas,

thank you very much for your support in this matter. of course you don't have to hurry to deal with the problem ;-)
i also thought about starting a fork to make all my adjustments available. for example i added a search, a photo gallery and the embedding of videos. maybe somebody's interested...

**Comment by bahnfrei** [comment]
Hi Niklas,

it seems the latest changes fixed this issue. Thanks a lot!
